name: Dual_Simultaneous_Stream

on:
  workflow_dispatch:
    inputs:
      channel_1_name:
        description: 'يوزر القناة الأولى'
        required: true
        default: 'OSAMAH'
        type: string
      stream_key_1:
        description: 'مفتاح البث للقناة الأولى (يوتيوب أو ريستريم)'
        required: true
        type: string
      channel_2_name:
        description: 'يوزر القناة الثانية'
        required: true
        default: 'اسم_القناة_الثانية'
        type: string
      stream_key_2:
        description: 'مفتاح البث للقناة الثانية (يوتيوب أو ريستريم)'
        required: true
        type: string
      platform:
        description: 'اختر المنصة المشتركة للثنتين (youtube أو restream)'
        required: true
        default: 'youtube'
        type: choice
        options:
          - youtube
          - restream

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install streamlink

      - name: Run Dual Stream Script
        env:
          C1_NAME: ${{ inputs.channel_1_name }}
          K1_KEY: ${{ inputs.stream_key_1 }}
          C2_NAME: ${{ inputs.channel_2_name }}
          K2_KEY: ${{ inputs.stream_key_2 }}
          PLATFORM: ${{ inputs.platform }}
        run: |
          python main.py
