name: Stream_Bot_2026

on:
  workflow_dispatch:
    inputs:
      channel_1_name:
        description: 'يوزر القناة الأولى (يوتيوب)'
        required: true
        default: 'Fwaz'
        type: string
      stream_key_1:
        description: 'مفتاح البث للقناة الأولى (يوتيوب)'
        required: true
        type: string
      channel_2_name:
        description: 'يوزر القناة الثانية (ريستريم)'
        required: true
        default: 'tmnaa'
        type: string
      stream_key_2:
        description: 'مفتاح البث للقناة الثانية (ريستريم)'
        required: true
        type: string

jobs:
  start_streaming:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install streamlink

      - name: Run Dual Stream
        env:
          C1_NAME: ${{ inputs.channel_1_name }}
          K1_KEY: ${{ inputs.stream_key_1 }}
          C2_NAME: ${{ inputs.channel_2_name }}
          K2_KEY: ${{ inputs.stream_key_2 }}
        run: |
          python main.py
