name: Start_Stream

on:
  workflow_dispatch:
    inputs:
      channel_choice:
        description: 'اختر القناة'
        required: true
        default: 'OSAMAH'
        type: choice
        options:
          - OSAMAH
          - اسم_القناة_الثانية_هنا
      platform:
        description: 'اختر المنصة (youtube أو restream)'
        required: true
        default: 'youtube'
        type: choice
        options:
          - youtube
          - restream
      stream_key:
        description: 'مفتاح البث (Stream Key)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install streamlink

      - name: Run Stream Script
        env:
          CHANNEL_CHOICE: ${{ inputs.channel_choice }}
          PLATFORM: ${{ inputs.platform }}
          STREAM_KEY: ${{ inputs.stream_key }}
        run: |
          python main.py

